apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-doeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-doeb
    app.kubernetes.io/part-of: jvm-build-suite-application-cbzj
  name: jvm-build-suite-component-doeb
  namespace: appstudio-e2e-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jvm-build-suite-component-doeb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jvm-build-suite-component-doeb
    spec:
      containers:
      - image: quay.io/psturc/test-images:8f6b2e192edb420e9ab6e1c883274a93
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
